### ISSUE TITLE
conflux-dag.js throws A LOT error

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/conflux-scan#185]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

Errors in browser devtool console related to dag graph

**If the current behavior is a bug, please provide the steps to reproduce.**

check discussions in #184 for details
![](https://user-images.githubusercontent.com/6622122/84637806-b77a0000-af28-11ea-9a63-ee466e8b496d.png)

**What is the expected behavior?**

no unintentional error in console

**Comment by 21paradox** [comment]
reproduce ways , page switching
 
![ezgif-2-1f04343f38bb](https://user-images.githubusercontent.com/6622122/84643670-bbaa1b80-af30-11ea-9117-2c24c250d25c.gif)


Hundred of errors are throwing in seconds. This will make the browser to be very very slow. Because too many error are occuring in the console.
